name: Publish Packages

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack Result.Net
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/Result.Net/Result.Net.csproj -o .
      - name: Push packages
        run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Upload assets to release
        run: |
          assets=()
          for asset in *.nupkg 
          do 
            assets+=("$asset")
          done
          for asset in *.snupkg 
          do 
            assets+=("$asset")
          done
          gh release upload ${{ github.event.release.tag_name }} "${assets[@]}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
